server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html index.htm;

  # Redireciona chamadas de API para o backend
  location /api/ {
    proxy_pass http://backend:3000/;
    proxy_set_header Host $host;
  }

  # Roteamento SPA (Angular)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Quando não encontrar arquivo, serve o index.html
  error_page 404 /index.html;
}