name: Deploy and Verify Kubernetes via EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: app-demo
      BACKEND_IMAGE: ${{ secrets.REGISTRY_USERNAME }}/backend
      FRONTEND_IMAGE: ${{ secrets.REGISTRY_USERNAME }}/frontend
      EC2_IP: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest,${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest,${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Apply manifests on remote K3s
        run: |
          ssh -i ec2_key.pem $EC2_USER@$EC2_IP << 'EOF'
            cd ~/k8s
            kubectl set image deployment/backend pedrobrantis/backend=${{ env.BACKEND_IMAGE }}:latest -n app-demo
            kubectl set image deployment/frontend web=${{ env.FRONTEND_IMAGE }}:latest -n app-demo
            kubectl rollout restart deployment/backend -n app-demo
            kubectl rollout restart deployment/frontend -n app-demo
            kubectl get pods -n app-demo
          EOF

      - name: Test public endpoints
        run: |
          echo "Testing backend..."
          curl -s -o /dev/null -w "%{http_code}\n" http://${{ env.EC2_IP }}:30045/api/v1/products?limit=3
          echo "Testing frontend..."
          curl -s -o /dev/null -w "%{http_code}\n" http://${{ env.EC2_IP }}:30050
          echo "Deployment completed successfully."